### ISSUE TITLE
can’t download album

### ISSUE THREAD

**Issue by jisa8438** [Masterolic/Spotify-repo#13]
can’t download album

**Comment by Masterolic** [comment]
Hello! Why? What error you got which branch are you using? Contact me via @masterolic at telegram https://masterolic.t.me

**Comment by jisa8438** [comment]
> Hello! Why? What error you got which branch are you using? Contact me via @Masterolic at telegram https://masterolic.t.me

Two Branches are the same，It just downloads one song of the album and shows “telegram says 500 error,so please try again later”，even if I ldownloads a single track，the error still exists
![image](https://github.com/Masterolic/Spotify-Downloader/assets/39065858/53bef57c-fa3c-4220-95f7-f77385d8910f)

**Comment by Masterolic** [comment]
> > Hello! Why? What error you got which branch are you using? Contact me via @Masterolic at telegram https://masterolic.t.me
> 
> Two Branches are the same，It just downloads one song of the album and shows “telegram says 500 error,so please try again later”，even if I ldownloads a single track，the error still exists ![image](https://user-images.githubusercontent.com/39065858/260280433-53bef57c-fa3c-4220-95f7-f77385d8910f.png)

Track had been successfully downloaded

The reason for 500 raised from telegram that you had filled the variable LOG_GROUP where the bot does not have rights to send message make sure the value is empty or not is admin in that chat

**Comment by jisa8438** [comment]
> > > Hello! Why? What error you got which branch are you using? Contact me via @Masterolic at telegram https://masterolic.t.me
> > 
> > 
> > Two Branches are the same，It just downloads one song of the album and shows “telegram says 500 error,so please try again later”，even if I ldownloads a single track，the error still exists ![image](https://user-images.githubusercontent.com/39065858/260280433-53bef57c-fa3c-4220-95f7-f77385d8910f.png)
> 
> Track had been successfully downloaded
> 
> The reason for 500 raised from telegram that you had filled the variable LOG_GROUP where the bot does not have rights to send message make sure the value is empty or not is admin in that chat

The LOG_GRAOUP value is always empty，the single track can be downloaded successfully，but the album can not，it just downloaded one track from the album and then stopped。
![image](https://github.com/Masterolic/Spotify-Downloader/assets/39065858/7c8f08f6-d933-42ba-9b5d-a475360469ac)

**Comment by Masterolic** [comment]
> > > > Hello! Why? What error you got which branch are you using? Contact me via @Masterolic at telegram https://masterolic.t.me
> > > 
> > > 
> > > Two Branches are the same，It just downloads one song of the album and shows “telegram says 500 error,so please try again later”，even if I ldownloads a single track，the error still exists ![image](https://user-images.githubusercontent.com/39065858/260280433-53bef57c-fa3c-4220-95f7-f77385d8910f.png)
> > 
> > 
> > Track had been successfully downloaded
> > The reason for 500 raised from telegram that you had filled the variable LOG_GROUP where the bot does not have rights to send message make sure the value is empty or not is admin in that chat
> 
> The LOG_GRAOUP value is always empty，the single track can be downloaded successfully，but the album can not，it just downloaded one track from the album and then stopped。 ![image](https://user-images.githubusercontent.com/39065858/260281490-7c8f08f6-d933-42ba-9b5d-a475360469ac.png)

Yes you are right bro :(

Just right now noticed forgotten to skip log method for None value thanks for bringing to  us 

Don't hesitate to report again  any issues :(❣️

**Comment by jisa8438** [comment]
> > > > > Hello! Why? What error you got which branch are you using? Contact me via @Masterolic at telegram https://masterolic.t.me
> > > > 
> > > > 
> > > > Two Branches are the same，It just downloads one song of the album and shows “telegram says 500 error,so please try again later”，even if I ldownloads a single track，the error still exists ![image](https://user-images.githubusercontent.com/39065858/260280433-53bef57c-fa3c-4220-95f7-f77385d8910f.png)
> > > 
> > > 
> > > Track had been successfully downloaded
> > > The reason for 500 raised from telegram that you had filled the variable LOG_GROUP where the bot does not have rights to send message make sure the value is empty or not is admin in that chat
> > 
> > 
> > The LOG_GRAOUP value is always empty，the single track can be downloaded successfully，but the album can not，it just downloaded one track from the album and then stopped。 ![image](https://user-images.githubusercontent.com/39065858/260281490-7c8f08f6-d933-42ba-9b5d-a475360469ac.png)
> 
> Yes you are right bro :(
> 
> Just right now noticed forgotten to skip log method for None value thanks for bringing to us
> 
> Don't hesitate to report again any issues :(❣️

Thanks for fixing,it's now perfect!

**Comment by Masterolic** [comment]
> > > > > > Hello! Why? What error you got which branch are you using? Contact me via @Masterolic at telegram https://masterolic.t.me
> > > > > 
> > > > > 
> > > > > Two Branches are the same，It just downloads one song of the album and shows “telegram says 500 error,so please try again later”，even if I ldownloads a single track，the error still exists ![image](https://user-images.githubusercontent.com/39065858/260280433-53bef57c-fa3c-4220-95f7-f77385d8910f.png)
> > > > 
> > > > 
> > > > Track had been successfully downloaded
> > > > The reason for 500 raised from telegram that you had filled the variable LOG_GROUP where the bot does not have rights to send message make sure the value is empty or not is admin in that chat
> > > 
> > > 
> > > The LOG_GRAOUP value is always empty，the single track can be downloaded successfully，but the album can not，it just downloaded one track from the album and then stopped。 ![image](https://user-images.githubusercontent.com/39065858/260281490-7c8f08f6-d933-42ba-9b5d-a475360469ac.png)
> > 
> > 
> > Yes you are right bro :(
> > Just right now noticed forgotten to skip log method for None value thanks for bringing to us
> > Don't hesitate to report again any issues :(❣️
> 
> Thanks for fixing,it's now perfect!

Welcome
