### ISSUE TITLE
It ran, but I couldn't find the song file.

### ISSUE THREAD

**Issue by l13304648** [Masterolic/Spotify-repo#18]
May I know how to find the downloaded song locally. I created Navichrome and I want the bot to download songs to the Navichrome directory.

**Comment by Masterolic** [comment]
Hello it usually download on /tmp/{a random integer directory} and song file 
https://github.com/Masterolic/Spotify-Downloader/blob/4c88f6a47022d46a38062e92be31496d1f31e148/mbot/plugins/spotify.py#L138

After sending it will delete the file from local
https://github.com/Masterolic/Spotify-Downloader/blob/4c88f6a47022d46a38062e92be31496d1f31e148/mbot/plugins/spotify.py#L560


You can use # front of it wherever it used to call rmtree(randomdir)

**Comment by l13304648** [comment]
> 你好它通常下载在/tmp/{一个随机整数目录}和歌曲文件上
> 
> https://github.com/Masterolic/Spotify-Downloader/blob/4c88f6a47022d46a38062e92be31496d1f31e148/mbot/plugins/spotify.py#L138
> 
> 发送后将从本地删除文件
> 
> https://github.com/Masterolic/Spotify-Downloader/blob/4c88f6a47022d46a38062e92be31496d1f31e148/mbot/plugins/spotify.py#L560
> 
> 您可以在调用 rmtree(randomdir) 的任何地方使用 #

Thank you very much, I successfully found the downloaded songs. I can now use the bot to add songs to my Navichrome.

**Comment by l13304648** [comment]
> Hello it usually download on /tmp/{a random integer directory} and song file
> 
> https://github.com/Masterolic/Spotify-Downloader/blob/4c88f6a47022d46a38062e92be31496d1f31e148/mbot/plugins/spotify.py#L138
> 
> After sending it will delete the file from local
> 
> https://github.com/Masterolic/Spotify-Downloader/blob/4c88f6a47022d46a38062e92be31496d1f31e148/mbot/plugins/spotify.py#L560
> 
> You can use # front of it wherever it used to call rmtree(randomdir)

Thank you very much, I successfully found the downloaded songs. I can now use the bot to add songs to my Navichrome.
